version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - NO_PROXY=$NO_PROXY
      - no_proxy=$no_proxy
    tty: true
    volumes:
        - .:/workspace
        - /workspace/build/
